version : "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: car_rental_db
    volumes:
      - mysql_data:/var/lib/mysql


  app:
    build: .
    container_name: carRental_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: car_rental_db
      DB_USER : root
      DB_PASSWORD: root@123

volumes:
  mysql_data:


