micronaut:
  application:
    name: carRental
  security:
    enabled: true
    basic-auth:
      enabled: false
    authentication: bearer
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SIGNATURE_SECRET:7f1e5b3e92c4e8d04a1f90877ae6ac3e9d68e3c99f8e1f2a4d675b75a389c1e3}
              jws-algorithm: HS256
    password:
      encoder:
        bcrypt:
          enabled: true

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:car_rental_db}?serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update



#datasources.default.url=jdbc:mysql://localhost:3306/car_rental_db?serverTimezone=UTC
#datasources.default.username=root
#datasources.default.password=
#datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
#datasources.default.dialect=MYSQL          # (db‑type is obsolete in Mn 4)
#
#
#micronaut.application.name=carRental
#jpa.default.properties.hibernate.hbm2ddl.auto=update